### PR TITLE
Transparency Slider in Context Menu (with typo fix)

### PR DESCRIPTION
**Pull request by dbzfanatic**
I've added a custom class for a slider to be in the context menu so the opacity can still be adjusted even if MainForm isn't showing properly. I also fixed a typo in the .iss file where the regkey was created as "First Run" instead of "FirstRun".

### CODE REVIEW

**Comment by mscrivo** [comment]
Thanks for the contribution! I'll check this out as soon as I get a spare moment

**Comment by dbzfanatic** [comment]
I swapped over to using MACTrackBar in a simplistic manner since it's in the context menu. It seems that even with a Margin of 0 a certain portion of the menu is reserved for the expansion arrow for sub-menus and, as far as I've found, there's no real way to bypass that easily.

**Comment by mscrivo** [comment]
This looks great, thank you for the contribution! I'll merge it in and try to get a release out asap.

**Comment by mscrivo** [comment]
You can try a build with your changes here: https://mscrivo.visualstudio.com/d1e953c0-d0ad-48e7-b6e1-a401a9b831f3/_apis/build/builds/450/artifacts?artifactName=artifact&api-version=7.1&%24format=zip

**Pull request merged**
